services:
  - type: web
    name: burnlab
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn letsLearn.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
